### ISSUE TITLE
Team: To-Do

### ISSUE THREAD

**Issue by ndangu** [rmlor/alby_pawdrobe#21]
- [x] CRUD implementations
- [x] resolve: merge conflicts
- [x] double check: citations
- [x]  double check: consistency in comments
- [x]  double check: consistency in console logs/alerts
- [x]  double check: consistency in update form header (dynamic) and pre-filled selected options
- [x]  double check: UI-friendly selected values
